from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.endpoints, name='endpoints'),
    path('users/', views.UsersView.as_view(), name='users'),
    path('students/', views.StudentView.as_view(), name='students'),
    path('students/<str:pk>/', views.StudentRetrieveUpdateDestroy.as_view(), name='indiviual_students'),
    path('delete-multiple-students/', views.DeleteMultipleStudentsView.as_view(), name='delete_multiple_students'),
    path('staff/', views.StaffView.as_view(), name='staff'),
    path('staff/<str:pk>/', views.StaffRetrieveUpdateDestroy.as_view(), name='indiviual_staff'),
    path('delete-multiple-staff/', views.DeleteMultipleStaffView.as_view(), name='delete_multiple_staff'),
    path('hr/', views.HRView.as_view(), name='hr'),
    path('delete-multiple-hr/', views.DeleteMultipleHRView.as_view(), name='delete_multiple_hr'),
    path('bursary/', views.BursaryView.as_view(), name='bursary'),
    path('store_keeper/', views.StoreKeeperView.as_view(), name='store_keeper'),
    path('other_staff/', views.OtherStaffView.as_view(), name='other_staff'),
    path('teachers/', views.TeachersView.as_view(), name='teachers'),
    path('parents/', views.ParentViews.as_view(), name='parents'),
    path('delete-multiple-parents/', views.DeleteMultipleParentsView.as_view(), name='delete_multiple_parents'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('request-to-change-password-form/', views.RequestToChangePasswordFormView.as_view(), name='request_to_change_password_form'),
    path('request-to-change-password/', views.RequestToChangePasswordView.as_view(), name='request_to_change_password'),
    path('request-to-change-password/<str:pk>/update-status/', views.RequestToChangePasswordStatusView.as_view(), name='request_to_change_password-update-status'),
    path('change-password/', views.ChangePasswordFormSerializer.as_view(), name='change_password'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('email/', views.EmailView.as_view(), name='Email' ),
    path('email/<str:pk>/', views.EmailRetrieveDestory.as_view(), name='indivicual_email' ),
    path('delete-multiple-email/', views.DeleteMultipleEmailsView.as_view(), name='delete_multiple_email' ),
    path('subjects/', views.SubjectsView.as_view(), name='subjects' ),
    path('subjects/<str:pk>/', views.SubjectsRetriveUpdateDestory.as_view(), name='indiviual_subjects' ),
    path('delete-multiple-subjects/', views.DeleteMultipleSubjectsView.as_view(), name='delete_multiple_subjects' ),
    path('student-class/', views.StudentClassView.as_view(), name='student_class' ),
    path('student-class/<str:pk>/', views.StudentClassRetriveUpdateDestory.as_view(), name='indiviual_student_class' ),
    path('delete-multiple-student-class/', views.DeleteMultipleStudentClassView.as_view(), name='delete_multiple_student_class' ),
    path('term/', views.TermView.as_view(), name='term' ),
    path('term/<str:pk>/', views.TermRetriveUpdateDestory.as_view(), name='indiviual_term' ),
    path('delete-multiple-term/', views.DeleteMultipleTermView.as_view(), name='delete_multiple_term' ),
    path('session/', views.SessionView.as_view(), name='session' ),
    path('session/<str:pk>/', views.SessionRetriveUpdateDestory.as_view(), name='indiviual_session' ),
    path('delete-multiple-session/', views.DeleteMultipleSessionView.as_view(), name='delete_multiple_session' ),
    path('admin-or-hr-notification/', views.AdminorHRNotificationView.as_view(), name='admin_or_hr_notification' ),
    path('admin-or-hr-notification/<str:pk>/', views.AdminorHRNotificationRetrieveUpdateDestroy.as_view(), name='indiviual_admin_or_hr_notification' ),
    path('delete-multiple-admin-or-hr-notification/', views.DeleteMultipleAdminorHRNotificationView.as_view(), name='delete_multiple_admin_or_hr_notification' ),
    path('school-notification/', views.SchoolNotificationView.as_view(), name='school_notification' ),
    path('school-notification/<str:pk>/', views.SchoolNotificationRetrieveUpdateDestroy.as_view(), name='indiviual_school_notification' ),
    path('delete-multiple-school-notification/', views.DeleteMultipleSchoolNotificationView.as_view(), name='delete_multiple_school_notification' ),
    path('class-notification/', views.ClassNotificationView.as_view(), name='class_notification' ),
    path('class-notification/<str:pk>/', views.ClassNotificationRetrieveUpdateDestroy.as_view(), name='indiviual_class_notification' ),
    path('delete-multiple-class-notification/', views.DeleteMultipleClassNotificationView.as_view(), name='delete_multiple_class_notification' ),
    # path('filtered-class-notification/', views.FilteredClassNotification.as_view(), name='filtered_class_notification' ),
    path('school-event/', views.SchoolEventView.as_view(), name='school_event' ),
    path('school-event/<str:pk>/', views.SchoolEventRetrieveUpdateDestroy.as_view(), name='indiviual_school_event' ),
    path('delete-multiple-school-event/', views.DeleteMultipleSchoolEventView.as_view(), name='delete_multiple_school_event' ),
    path('scratch-cards/generate/', views.GenerateScratchCardView.as_view(), name='generate-scratch-cards'),
    
    # ---------------------- Results -------------------------- #
    path('student-result/', views.StudentResultListCreateApiView.as_view(), name='student_result'),
    path('student-result/<str:pk>/', views.StudentResultRetrieveUpdateDestroyApiView.as_view(), name='result-details'),
    path('check-result/', views.CheckStudentResultView.as_view(), name='check_result'),
    path('subject-result/', views.SubjectResultListCreateApiView.as_view(), name='subject_result'),
    path('subject-result/<str:pk>/', views.SubjectResultRetrieveUpdateDestroyApiView.as_view(), name='subject_result_details'),
    
    path('e-result/', views.EResultView.as_view(), name='e_result'),
    path('e-result/<str:pk>/', views.EResultRetrieveUpdateDestroyApiView.as_view(), name='indiviual_e_result'),
    path('delete-multiple-e-result/', views.DeleteMultipleEResultView.as_view(), name='delete_multiple_e_result'),
    path('check-e-result/', views.CheckEResultView.as_view(), name='check_e_result'),
    # ---------------------- End -------------------------- #
        
    path('scheme-of-work/', views.SchemeOfWorkView.as_view(), name='scheme_of_work' ),
    path('scheme-of-work/<str:pk>/', views.SchemeOfWorkRetrieveUpdateDestroy.as_view(), name='indiviual_scheme_of_work' ),
    path('delete-multiple-scheme-of-work/', views.DeleteMultipleSchemeOfWorkView.as_view(), name='delete_multiple_scheme_of_work' ),
    
    path('assignment/', views.AssignmentView.as_view(), name='assignment' ),
    path('assignment/<str:pk>/', views.AssignmentRetrieveUpdateDestroy.as_view(), name='indiviual_assignment' ),
    path('delete-multiple-assignment/', views.DeleteMultipleAssignmentView.as_view(), name='delete_multiple_assignment' ),
    
    path('assignment-submission/', views.AssignmentSubmissionView.as_view(), name='assignment_submission' ),
    path('assignment-submission/<str:pk>/', views.AssignmentSubmissionRetrieveUpdateDestroy.as_view(), name='indiviual_assignment_submission' ),
    path('assignment-submission/<str:pk>/update/', views.UpdateAssignmentSubmissionView.as_view(), name='assignment_update' ),
    path('delete-multiple-assignment-submssion/', views.DeleteMultipleAssignmentSubmssionView.as_view(), name='delete_multiple_assignment_submission' ),
    
    path('class-timetable/', views.ClassTimetableView.as_view(), name='class_timetable' ),
    path('class-timetable/<str:pk>/', views.ClassTimetableRetrieveUpdateDestroy.as_view(), name='indiviual_class_timetable' ),
    path('delete-multiple-class-timetable/', views.DeleteMultipleClassTimetableView.as_view(), name='delete_multiple_class_timetable' ),
]
